### ISSUE TITLE
Transfer to Ably GitHub

### ISSUE THREAD

**Issue by lawrence-forooghian** [ably-labs/test-observability#2]

**Comment by lawrence-forooghian** [comment]
@quintinwillison said this needs:

- `LICENCE`
- `COPYRIGHT`

(take them from some other Ably repo, and then request transfer to @ably-labs)

**Comment by QuintinWillison** [comment]
It's here and @lawrence-forooghian has added `LICENCE` and `COPYRIGHT` files.
